//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ColorService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let ImageApp = _ModuleRegistry.module("ImageApp");

    Slice.defineSequence(ImageApp, "ByteSeqHelper", "Ice.ByteHelper", true);

    const iceC_ImageApp_ColorService_ids = [
        "::Ice::Object",
        "::ImageApp::ColorService"
    ];

    ImageApp.ColorService = class extends Ice.Object
    {
    };

    ImageApp.ColorServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(ImageApp.ColorService, ImageApp.ColorServicePrx, iceC_ImageApp_ColorService_ids, 1,
    {
        "Color2BW": [, , , , ["ImageApp.ByteSeqHelper"], [["ImageApp.ByteSeqHelper"]], , , , ]
    });
    exports.ImageApp = ImageApp;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
