# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.10
#
# <auto-generated>
#
# Generated from file `ColorService.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module ImageApp
_M_ImageApp = Ice.openModule('ImageApp')
__name__ = 'ImageApp'

if '_t_ByteSeq' not in _M_ImageApp.__dict__:
    _M_ImageApp._t_ByteSeq = IcePy.defineSequence('::ImageApp::ByteSeq', (), IcePy._t_byte)

_M_ImageApp._t_ColorService = IcePy.defineValue('::ImageApp::ColorService', Ice.Value, -1, (), False, True, None, ())

if 'ColorServicePrx' not in _M_ImageApp.__dict__:
    _M_ImageApp.ColorServicePrx = Ice.createTempClass()
    class ColorServicePrx(Ice.ObjectPrx):

        def Color2BW(self, image, context=None):
            return _M_ImageApp.ColorService._op_Color2BW.invoke(self, ((image, ), context))

        def Color2BWAsync(self, image, context=None):
            return _M_ImageApp.ColorService._op_Color2BW.invokeAsync(self, ((image, ), context))

        def begin_Color2BW(self, image, _response=None, _ex=None, _sent=None, context=None):
            return _M_ImageApp.ColorService._op_Color2BW.begin(self, ((image, ), _response, _ex, _sent, context))

        def end_Color2BW(self, _r):
            return _M_ImageApp.ColorService._op_Color2BW.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_ImageApp.ColorServicePrx.ice_checkedCast(proxy, '::ImageApp::ColorService', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_ImageApp.ColorServicePrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::ImageApp::ColorService'
    _M_ImageApp._t_ColorServicePrx = IcePy.defineProxy('::ImageApp::ColorService', ColorServicePrx)

    _M_ImageApp.ColorServicePrx = ColorServicePrx
    del ColorServicePrx

    _M_ImageApp.ColorService = Ice.createTempClass()
    class ColorService(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::ImageApp::ColorService')

        def ice_id(self, current=None):
            return '::ImageApp::ColorService'

        @staticmethod
        def ice_staticId():
            return '::ImageApp::ColorService'

        def Color2BW(self, image, current=None):
            raise NotImplementedError("servant method 'Color2BW' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_ImageApp._t_ColorServiceDisp)

        __repr__ = __str__

    _M_ImageApp._t_ColorServiceDisp = IcePy.defineClass('::ImageApp::ColorService', ColorService, (), None, ())
    ColorService._ice_type = _M_ImageApp._t_ColorServiceDisp

    ColorService._op_Color2BW = IcePy.Operation('Color2BW', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_ImageApp._t_ByteSeq, False, 0),), (), ((), _M_ImageApp._t_ByteSeq, False, 0), ())

    _M_ImageApp.ColorService = ColorService
    del ColorService

# End of module ImageApp
